# Generated by Django 2.2.6 on 2019-11-21 20:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this Context. Must be unique within the Team.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug for this Context. Must be unique within the Team."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of this context. Markdown is supported."
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "get_latest_by": "created",
                "abstract": False,
            },
        )
    ]
