# Generated by Django 2.2.6 on 2019-10-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("context", "0001_initial"), ("team", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="context",
            name="team",
            field=models.ForeignKey(
                help_text="The Team to which this Context belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contexts",
                to="team.Team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="context", unique_together={("slug", "team"), ("name", "team")}
        ),
    ]
