# Generated by Django 2.2.6 on 2019-11-21 20:51

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("team", "0001_initial"),
        ("context", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="context",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="utils.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="context",
            name="team",
            field=models.ForeignKey(
                help_text="The Team to which this Context belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contexts",
                to="team.Team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="context", unique_together={("slug", "team"), ("name", "team")}
        ),
    ]
