# Generated by Django 2.2.6 on 2019-10-27 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("category", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this Item. Must be unique within the Category.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description for this Item (optional).",
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug for this Item. Must be unique within the Category.",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The Category on which this Item is based",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="category.Category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": (("add_review", "Add Review belonging to this Item"),),
                "unique_together": {("slug", "category"), ("name", "category")},
            },
        )
    ]
