# Generated by Django 2.2.2 on 2019-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("item", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(
                help_text="The slug for this Item. Must be unique within the Category.",
                max_length=100,
            ),
        )
    ]
