# Generated by Django 2.2.6 on 2019-10-17 18:58

from django.db import migrations, models
import utils.uploads
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        help_text="The file",
                        upload_to=utils.uploads.get_attachment_path,
                    ),
                ),
                (
                    "mimetype",
                    models.CharField(
                        help_text="The mimetype of this file as detected by python-magic on upload.",
                        max_length=255,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(help_text="The size in bytes of this file"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="The description for this attachment.",
                        max_length=255,
                    ),
                ),
            ],
            options={"ordering": ["pk"]},
        )
    ]
