# Generated by Django 2.2.6 on 2019-10-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("attachment", "0001_initial"), ("review", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="review",
            field=models.ForeignKey(
                help_text="The Review to which this Attachment belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="review.Review",
            ),
        )
    ]
