# Generated by Django 2.1.2 on 2018-11-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated')),
                ('admin', models.BooleanField(default=False, help_text='This member is an admin of this Team')),
                ('actor', models.ForeignKey(help_text='The Actor to which this Membership belongs', on_delete=django.db.models.deletion.PROTECT, to='actor.Actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated')),
                ('name', models.CharField(help_text='The name of the Team', max_length=128)),
                ('slug', models.SlugField(help_text='The slug for this Team', unique=True)),
                ('founder', models.ForeignKey(help_text='The founder of this Team', on_delete=django.db.models.deletion.PROTECT, related_name='founded_teams', to='actor.Actor')),
                ('members', models.ManyToManyField(help_text='The current members of this Team', related_name='memberships', through='team.Membership', to='actor.Actor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(help_text='The Group to which this Membership belongs', on_delete=django.db.models.deletion.PROTECT, to='team.Team'),
        ),
    ]
