# Generated by Django 2.2.2 on 2019-06-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('actor', 'team')},
        ),
    ]
