# Generated by Django 2.2.6 on 2019-11-21 20:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The plural name of this Category. Must be unique within the Team. Changing the name also changes the URL slug, which means old links will stop working.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug for this Category. Must be unique within the Team.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of this category. Markdown is supported."
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=10,
                        help_text="Change the weight of a Category to change sorting. Heavier Categories sink to the bottom. Categories with the same weight are sorted by name.",
                    ),
                ),
            ],
            options={
                "ordering": ["weight", "name"],
                "permissions": (
                    ("add_item", "Add Item belonging to this Category"),
                    ("add_fact", "Add Fact for this Category"),
                    ("add_rating", "Add Rating for this Category"),
                ),
                "get_latest_by": "created",
                "abstract": False,
            },
        )
    ]
