# Generated by Django 2.2.6 on 2019-11-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("category", "0001_initial"), ("context", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="default_context",
            field=models.ForeignKey(
                blank=True,
                help_text="The default Context for new Reviews for Items in this Category. Leave blank to have no default.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="context.Context",
            ),
        )
    ]
