# Generated by Django 2.2.2 on 2019-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("category", "0003_auto_20190430_1211")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="The slug for this Category. Must be unique within the Team.",
                max_length=100,
            ),
        )
    ]
