# Generated by Django 2.2.6 on 2019-10-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("category", "0005_auto_20190923_1509")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["weight", "name"],
                "permissions": (
                    ("add_item", "Add Item belonging to this Category"),
                    ("add_fact", "Add Fact for this Category"),
                    ("add_rating", "Add Rating for this Category"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="The name of this Category. Must be unique within the Team. Changing the name also changes the URL slug, which means old links will stop working.",
                max_length=100,
            ),
        ),
    ]
