# Generated by Django 2.1.2 on 2018-11-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated')),
                ('review', models.TextField(blank=True, help_text='The review of this Item')),
                ('actor', models.ForeignKey(help_text='The Actor who made this Review', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='actor.Actor')),
                ('item', models.ForeignKey(help_text='The Item this Review applies to', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='item.Item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('actor', 'item')},
        ),
    ]
