# Generated by Django 2.1.2 on 2018-11-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
        ('category', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated')),
                ('name', models.CharField(help_text='The name of this Property. Must be unique within the Category.', max_length=100)),
                ('slug', models.SlugField(help_text='The slug for this Property. Must be unique within the Category.')),
                ('description', models.CharField(help_text='A short description of this Property, 255 characters or less.', max_length=255)),
                ('max_rating', models.PositiveIntegerField(default=5, help_text='The maximum rating (number of stars) for this Property. Defaults to 5, maximum 100.')),
                ('icon', models.CharField(default='fas fa-star', help_text='The icon to use when visually displaying the ratings for this Property', max_length=50)),
                ('category', models.ForeignKey(help_text='The Category on which this Item is based', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='category.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated')),
                ('rating', models.PositiveIntegerField(help_text='The rating for this Property')),
                ('comment', models.CharField(blank=True, help_text='An optional short comment related to this specific rating. 255 character limit.', max_length=255)),
                ('actor', models.ForeignKey(help_text='The Actor who made this Rating', on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='actor.Actor')),
                ('item', models.ForeignKey(help_text='The Item this Rating applies to', on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='item.Item')),
                ('property', models.ForeignKey(help_text='The Property this Rating applies to', on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='rating.Property')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('item', 'actor', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('name', 'category'), ('slug', 'category')},
        ),
    ]
