# Generated by Django 2.2.2 on 2019-09-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rating", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="slug",
            field=models.SlugField(
                help_text="The slug for this Rating. Must be unique within this Category.",
                max_length=100,
            ),
        )
    ]
