# Generated by Django 2.2.6 on 2019-12-13 09:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [("thread", "0002_auto_20191121_2051")]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="utils.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        )
    ]
