# Generated by Django 2.2.6 on 2019-11-21 20:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this Forum, such as 'General Discussion' or 'Off-Topic'",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug for this Forum. Must be unique in the Team.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="The description of this Forum"),
                ),
                (
                    "allow_new_threads",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to disallow creation of new Threads in this Forum.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "permissions": (("add_thread", "Add Thread in this Forum"),),
                "get_latest_by": "created",
                "abstract": False,
            },
        )
    ]
