# Generated by Django 2.2.6 on 2019-10-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("vote", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="An optional short comment related to this specific vote. 1000 character limit.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="created",
            field=models.DateTimeField(
                help_text="The date and time when this object was created."
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="updated",
            field=models.DateTimeField(
                help_text="The date and time when this object was last updated."
            ),
        ),
    ]
