# Generated by Django 2.2.6 on 2019-11-21 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("actor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was created.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The date and time when this object was last updated.",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="The PK/UUID of the object this Comment relates to.",
                        max_length=36,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="The subject of this Comment.", max_length=100
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The body of this Comment. Markdown is supported."
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The Actor who made this Comment.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="actor.Actor",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The Django content_type of the model for the object this Comment relates to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="contenttypes.ContentType",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Comment this Comment is a reply to, if any",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comment.Comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        )
    ]
