# Generated by Django 2.2.6 on 2019-11-21 20:51

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0001_initial"),
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="utils.UUIDTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        )
    ]
