# Generated by Django 2.2.6 on 2019-10-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [("eav", "0006_auto_20191012_2124")]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("eav.attribute",),
        )
    ]
